---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present

- name: Download the Docker apt key.
  get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: "{{ docker_apt_gpg_key_local_path }}.armored"
    checksum: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
    owner: root
    group: root
    mode: 0644

- name: Dearmor the downloaded GPG key.
  shell: "gpg --dearmor < {{ docker_apt_gpg_key_local_path }}.armored > {{ docker_apt_gpg_key_local_path }}"
  args:
    creates: "{{ docker_apt_gpg_key_local_path }}"

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    filename: "docker"
    state: present
    update_cache: true
